### ISSUE TITLE
npm && CommonJS support

### ISSUE THREAD

**Issue by jamesfzhang** [transloadit/jquery-sdk#47]
Are there any plans to support installing this SDK via npm & CommonJS? Thanks.

**Comment by kvz** [comment]
We'll discuss with the author if that's on the roadmap, but chances are we might not do that anymore since we're already building this capability inside http://uppy.io, in some ways, the successor to this project (but it does much more).

It will still take some time before that's in a usable state though, so the question for you is, is this a blocking issue for you? Could you share some more about your use case? Maybe there are other ways we can help you still

**Comment by jamesfzhang** [comment]
Hi, thanks for the quick response. It's not a blocking issue for me at all, I was just curious. Uppy seems very cool, will it be replacing transloadit?

**Comment by kvz** [comment]
Once it's done, it will be the recommended way to Integrate Transloadit's uploading and encoding capabilities with browsers, so in that sense it will be replacing Transloadit's jquery-sdk (for those who want to migrate to something more powerful and that can afford to drop supporting IE<=8 for instance). The jquery-sdk will only receive security/bug patches then, for users that can't or don't want to migrate.

**Comment by jamesfzhang** [comment]
Great, thanks for the info!
