### ISSUE TITLE
Release new version to NPM?

### ISSUE THREAD

**Issue by louim** [transloadit/jquery-sdk#67]
Hey!
The last version of this plugin released on [NPM is 2.7.1](https://www.npmjs.com/package/transloadit-jquery),  but the latest version in this repo is 3.0.13. 
Can we get a new version on NPM?

**Comment by louim** [comment]
Ping @tim-kos and @kvz, as the listed package publishers on NPM.

**Comment by kvz** [comment]
Sorry for the delay and thanks for the headsup @louim @tim-kos has this on his radar!

In the meantime I'd also like to invite you to check out [Uppy](https://uppy.io), most of Transloadit's love and care is going there these days, and it could improve speed, reliability, and ux for your users.

**Comment by louim** [comment]
Hi @kvz, we have been eyeing Uppy, but it required a bit more internal refactoring that we had the bandwith to do right now. We will definitely look more into it in the future.

**Comment by tim-kos** [comment]
The trouble is that a different person published a fork under that npm name: https://github.com/k41n/jquery-sdk

We need to ask them to pull from upstream and update publish a new version.

**Comment by louim** [comment]
@tim-kos You could rename the `package.json` to match the name of the package you have control of (this one: https://www.npmjs.com/package/transloadit-jquery)  instead of pushing it to https://www.npmjs.com/package/transloadit-jquery-sdk. Or you could publish in under an org name, for example `@transloadit/jquery-sdk`.

**Comment by kvz** [comment]
Sorry for the long wait, we never published this thing to npm before so everybody was a bit puzzled. But it's a good suggestion and I've executed on it just now:

```bash
+ @transloadit/jquery-sdk@3.3.2
```

Please do let me know if the package is OK like this, I'm unsure how you intend to use it since we don't offer any commonjs exports or similar. It's just the raw build files that you'd typically just require via `<script>` tags. Uppy has more fanciness but we don't really plan on adding that here. But suggestions for small tweaks to make it usable for you, or PRs, are welcome. 

@k41n we're now publishing this project to NPM ourselves, thanks for having our backs : ) Would it make sense to deprecate your module and point to `@transloadit/jquery-sdk` going forward?
