### ISSUE TITLE
Unexpected token ':'

### ISSUE THREAD

**Issue by paskuale75** [transloadit/jquery-sdk#86]
If I import uppy.min.js.map into my page, console return me:
`Uncaught SyntaxError: Unexpected token ':'`  (at line n.2)

Thanks

**Comment by Acconut** [comment]
Hi there, I want to note two things:
- This is the repository for the jQuery SDK. You likely wanted to open an issue in the Uppy repository at https://github.com/transloadit/uppy
- Are you sure you want to import uppy.min.js.map instead of **uppy.min.js**? The .map file does not contain any JavaScript code, so it won't provide the Uppy API to you.

**Comment by paskuale75** [comment]
You are right, thanks for suggestion  ;)
